### ISSUE TITLE
Create UI/UX on Figma

### ISSUE THREAD

**Issue by mariigg** [Devfolo/Frontend#1]
Blobbee pls complete the first stage of the UI, Latest tomorrow as discussed.

**Comment by Blobbee** [comment]
ok

**Comment by Blobbee** [comment]
Currently working on it

**Comment by Blobbee** [comment]
Here's the work progress https://www.figma.com/file/g9CZT2PrPZFW9DqPfO1gqs/Devfolo-UI?node-id=1%3A3
